apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rag-chatbot.fullname" . }}-secrets
  labels:
    {{- include "rag-chatbot.labels" . | nindent 4 }}
type: Opaque
data:
  # Keys must be base64 encoded. Helm's toYaml | b64enc will handle this.
  # For production, these should be supplied securely, e.g., via `helm install --set-string`
  # or an external secret management system.
  OPENAI_API_KEY: {{ .Values.secretEnv.OPENAI_API_KEY | b64enc | quote }}
  PINECONE_API_KEY: {{ .Values.secretEnv.PINECONE_API_KEY | b64enc | quote }}
  PINECONE_ENVIRONMENT: {{ .Values.secretEnv.PINECONE_ENVIRONMENT | b64enc | quote }}
